<?php

/**
 * @file
 * Contains rp_site_generator.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_site_generator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_site_generator module.
    case 'help.page.rp_site_generator':
      $output = '';
      $output .= '<h3>' . t('About Site Generation module') . '</h3>';
      $output .= '<p>' . t(document()) . '</p>';
      $output .= '<p>' . t('<a class="button button--primary js-form-submit form-submit" href="/admin/siteGenerator/form/site_generator">Generate now!!!</a>') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function rp_site_generator_theme() {
  return [
    'rp_site_generator' => [
      'render element' => 'children',
    ],
  ];
}


function document(){
  $req='
    <h3>Basic Requirements</h3>
          - Apache Virtualhost<br>
          - Data base (mysql or posgrest)
  ';
  $configFile='
     <h3>Config File - Example</h3>
        <pre>
           {
            "multisite" : "content.repository.katso-urheilua.com",  
            "siteDB": "content_repository_katso_urheilua",
            "id_site": "4",
          
            "base_THEME":"stevethemebase",
            "base_THEME_CONF":"rp_cms_steve_base_config",
            "admima_theme":"fortytwo_admin",
            "langcode":"en",
            "site_name":"katso.urheilua.cu Content Repository",
            "site_mail":"contact@client1.dev",
            "account_name":"admin",
            "account_mail":"contact@client1.dev",
            "account_pass":"admin",
          
            "type":"mysql",
            "host":"localhost",
            "name":"content_repository_katso_urheilua",
            "user":"root",
            "pass":"root",
            "port":"3316",
          
            "base_site_api_id":"4",
            "base_site_url":"http://content.repository.katso-urheilua.com",
            "site_url_api":"http://user.controller.cu/",  
            "site_def_channel":"1",
          
            "langcode_code":"da",
            "langcode_url":"http://ftp.drupal.org/files/translations/8.x/drupal/drupal-8.6.0-beta2.da.po",
            "langcode_filename":"drupal-8.6.0-beta2.da.po"
          }
        <pre>  
    ';
  return  $req.$configFile;


}
