<?php

/**
 * @file
 * Contains rp_cms_steve_integration.module.
 */
use Drupal\Core\Url;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\rp_cms_steve_integration\Controller\SteveFrontendControler;

/**
 * Implements hook_help().
 */
function rp_cms_steve_integration_help($route_name, RouteMatchInterface $route_match)
{

    switch ($route_name) {
        // Main module help for the rp_cms_steve_integration module.
        case 'help.page.rp_cms_steve_integration':
            $output = '';
            $output .= '<h3>' . t('About Steve Integration Module') . '</h3>';
            $output .= '<p>' . t('Provide integration between Backend and Frontend on Steve CMS project') . '</p>';


            $output .= '<div class="help_info_module"><h3>Events</h3><p>Take a look of site sport events. Edit or see it in the live site</p>';
            $output .= '<a href="/admin/steve_integration/form/event_filters" class="button button--primary button--small">Go to "Events Filter "</a><br></div>';



            $output .= '<div class="help_info_module"><h3>Import</h3><p>Import data from STEVE API</p>';
            $output .= '<a href="/admin/import_from_api" class="button button--primary button--small">Import Data</a><br>';

            $output .= '<p>Import data from Content Repository </p>';
            $output .= '<a href="/admin/import_from_api" class="button button--primary button--small">Import Data </a><br></div>';


            $output .= '<div class="help_info_module"><h3>Our Plugins.</h3>';
            $output .= '<p>We have a long list of plugins, please take a look.</p>
                          Example :
                          <ul>
                          <li>Home Page Top/head</li>
                          <li>Home Page Partners</li>
                          <li>Event Page Content</li>
                          </ul>
                          <br>
                      ';
            $output .= '<a href="/admin/structure/block" class="button button--primary button--small">Go to "Block layout"</a><br></div>';


            return $output;
        default:
    }
}

/**
 * Implements hook_theme().
 */
function rp_cms_steve_integration_theme()
{
    return [
        'siteflagmenuplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'languages' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/GeneralSite/siteflagmenuplugin',
            ],
        'sitefooterplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/GeneralSite/sitefooterplugin',
            ],
        'sitesubmenuplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/GeneralSite/sitesubmenuplugin',
            ],
        'homebodyplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/HomePage/homebodyplugin',
            ],
        'homefooterplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/HomePage/homefooterplugin',
            ],
        'homeheadplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/HomePage/homeheadplugin',
            ],
        'homepartnerplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/HomePage/homepartnerplugin',
            ],
        'sporthomeheadplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'background' => NULL,
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/SportPage/sporthomeheadplugin',
            ],
        'sporthomepopularmatchplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/SportPage/sporthomepopularmatchplugin',
            ],
        'sporthomescheduleplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/SportPage/sporthomescheduleplugin',
            ],
        'sporthomestreamlistplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/SportPage/sporthomestreamlistplugin',
            ],
        'sporthomefooterplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/SportPage/sporthomefooterplugin',
            ],
        'sportblogheadplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'background' => NULL
                ],
                'template' => 'SteveBaseFrontend/Blog/sportbloghead',
            ],
        'sportblogbodyplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/Blog/sportblogbody',
            ],
        'sportblogfooterplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/Blog/sportblogfooter',
            ],
        'eventpagecontentplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/Events/eventpagecontentplugin',
            ],
        'eventpagefooterplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                ],
                'template' => 'SteveBaseFrontend/Events/eventpagefooterplugin',
            ],
        'eventpageheadplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'background' => NULL,
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/Events/eventpageheadplugin',
            ],
        'eventpagestreamlistplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/Events/eventpagestreamlistplugin',
            ],
        'sportlivestreamcarruselplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'background' => NULL,
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/LiveStream/sportlivestreamcarruselplugin',
            ],
        'sportlivestreamlistplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/LiveStream/sportlivestreamlistplugin',
            ],
        'sportlivestreamschedulefooterplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/LiveStream/sportlivestreamschedulefooterplugin',
            ],
        'streamproviderheadplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/StreamProvider/streamproviderheadplugin',
            ],
        'streamproviderbodyplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/StreamProvider/streamproviderbodyplugin',
            ],
        'colormainmenuplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/Menu/colormainmenuplugin',
            ],
        'livestreamreviewspage' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/LiveStreamReviews/livestreamreviewspage',
            ],
        'livestreamreviewsplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/LiveStreamReviews/livestreamreviewsplugin',
            ],
        'livestreamreviewpage' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/LiveStreamReviews/livestreamreviewpage',
            ],
        'custombreadcrumbsplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'breadcrumbs' => []
                ],
                'template' => 'SteveBaseFrontend/Breadcrumbs/custombreadcrumbsplugin',
            ],
        'participantheadplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'background' => NULL,
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/Participant/participantheadplugin',
            ],
        'participantbodyplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/Participant/participantbodyplugin',
            ],
        'participantlistplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/Participant/participantlistplugin',
            ],
        'participantscheduleplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/Participant/participantscheduleplugin',
            ],
        'sportsandtournamentsheadplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'background' => NULL,
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/SportsAndTournaments/sportsandtournamentsheadplugin',
            ],
        'sportsandtournamentsbodyplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => []
                ],
                'template' => 'SteveBaseFrontend/SportsAndTournaments/sportsandtournamentsbodyplugin',
            ],
        'sportsandtournamentslistplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/SportsAndTournaments/sportsandtournamentslistplugin',
            ],
        'sportsandtournamentsscheduleplugin' =>
            [
                'variables' => [
                    'titulo' => 'Udbydere af Live Stream',
                    'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
                    'tags' => [],
                    'colors' => []
                ],
                'template' => 'SteveBaseFrontend/SportsAndTournaments/sportsandtournamentsscheduleplugin',
            ],
        ];
    }

/**
 * Implements hook_toolbar().
 *
 * function rp_cms_steve_integration() {
 * $items = array();
 * $items['rp_base'] = array(
 * '#attached' => array('library' => array('rp_cms_steve_integration/steveModuleLibraries')),
 * );
 * return $items;
 * }
 */

// From core/modules/contextual/contextual.module.
function rp_cms_steve_integration_page_attachments(array &$page)
{
    $page['#attached']['library'][] = 'rp_cms_steve_integration/steveModuleLibrariesGeneral';
    
	if(!\Drupal::service('router.admin_context')->isAdminRoute() && \Drupal::service('theme.manager')->getActiveTheme()->getName() == 'stevethemebase'){
        $page['#attached']['library'][] = 'rp_cms_steve_integration/steveModuleLibraries';
    }

    if(pager_find_page() > 0){
        foreach ($page['#attached']['html_head'] as $index => $attach) {
            if($attach[1] == 'canonical_url'){
                unset($page['#attached']['html_head'][$index]);
            }
        }
    }
}

function rp_cms_steve_integration_preprocess_pager(&$variables){
    $classObj = new SteveFrontendControler();

    if(isset($variables['items']['previous'])){
        $variables['#attached']['html_head_link'][] = [
            [
                'rel' => 'prev',
                'href' => Url::fromRoute('<current>', [], ['absolute' => 'true'])->toString().$variables['items']['previous']['href']
            ],
            TRUE
        ];
    }

    if(isset($variables['items']['next'])){
        $variables['#attached']['html_head_link'][] = [
            [
                'rel' => 'next',
                'href' => Url::fromRoute('<current>', [], ['absolute' => 'true'])->toString().$variables['items']['next']['href']
            ],
            TRUE
        ];
    }

    if(pager_find_page() > 0){
        $variables['#attached']['html_head_link'][] = [
            [
                'rel' => 'canonical',
                'href' => \Drupal::request()->getSchemeAndHttpHost().\Drupal::request()->getRequestUri()
            ],
            TRUE
        ];
    }

    $variables['#attached']['html_head_link'][] = [
        [
            'rel' => 'shortlink',
            'href' => \Drupal::request()->getSchemeAndHttpHost().\Drupal::request()->getRequestUri()
        ],
        TRUE
    ];

    $variables['colors'] = $classObj->getColors();
}

function rp_cms_steve_integration_preprocess_block(&$vars){
    $blocks = ['language_block:language_interface', 'sportlivestreamcarruselplugin', 'siteflagmenuplugin', 'sitefooterplugin', 'homeheadplugin'];

    foreach ($blocks as $block) {
        if($vars['elements']['#plugin_id'] == $block){
            $vars['#cache']['max-age'] = 0;
        }
    }

}