<?php

/**
 * @file
 * Contains rp_site.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_site_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_site module.
    case 'help.page.rp_site':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RP Site entity') . '</p>';
      return $output;

    default:
  }
}
