<?php
/**
 * @file
 * Contains articlestreamprovider.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function articlestreamprovider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the articlestreamprovider module.
    case 'help.page.articlestreamprovider':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Stream Providers List') . '</p>';
      return $output;

    default:
  }
}
/**
 * Implements hook_theme().
 */
function articlestreamprovider_theme($existing, $type, $theme, $path) {
  return ['steram_theme' =>
            [
              'variables' => [
                'titulo' => 'Título por defecto',
                'descripcion' => 'descripción por defecto',
                'tags' => array()
              ],
              'template' => 'articlestreamprovider'
            ]
        ];
}
