<?php

/**
 * @file
 * Contains rp_cms_steve_integration_live_fodbald_streams.module.
 */
 
/**
 * Implements hook_theme().
 */

function rp_cms_steve_integration_live_fodbald_streams_theme()
{
    return [
        //PAGES
        'fodbaldstreamsprogrampage' => [
            'template' => 'Pages/fodbaldstreamsprogrampage'
        ],
        'fodbaldstreamsleaguespage' => [
            'template' => 'Pages/fodbaldstreamsleaguespage'
        ],
        'fodbaldstreamsteamspage' => [
            'template' => 'Pages/fodbaldstreamsteamspage'
        ],
        //GENERAL
        'fodbaldstreamsheaderplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Site/fodbaldstreamsheaderplugin'
        ],
        'fodbaldstreamsfooterplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Site/fodbaldstreamsfooterplugin'
        ],
        'fodbaldstreamsfootersecondaryplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => [],
                'front' => FALSE,
            ],
            'template' => 'Site/fodbaldstreamsfootersecondaryplugin'
        ],
        'fodbaldstreamspopupplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => [],
            ],
            'template' => 'Site/fodbaldstreamspopupplugin'
        ],

        //HOME PAGE
        'fodbaldstreamshomeheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldstreamshomeheadplugin'
        ],
        'fodbaldstreamshometitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldstreamshometitleplugin'
        ],
        'fodbaldstreamshomematchesplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldstreamshomematchesplugin'
        ],
        'fodbaldstreamshomepreviewsplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldstreamshomepreviewsplugin'
        ],
        
        
        //PROGRAM
        'fodbaldstreamsprogramheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Program/fodbaldstreamsprogramheadplugin'
        ],
        'fodbaldstreamsprogramtitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Program/fodbaldstreamsprogramtitleplugin'
        ],
        'fodbaldstreamsprogrammatchlistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Program/fodbaldstreamsprogrammatchlistplugin'
        ],
        
        //LEAGUES
        'fodbaldstreamsleaguesheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Leagues/fodbaldstreamsleaguesheadplugin'
        ],
        'fodbaldstreamsleaguestitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Leagues/fodbaldstreamsleaguestitleplugin'
        ],
        'fodbaldstreamsleagueslistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Leagues/fodbaldstreamsleagueslistplugin'
        ],
        
        //TEAMS
        'fodbaldstreamsteamsheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Teams/fodbaldstreamsteamsheadplugin'
        ],
        'fodbaldstreamsteamstitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Teams/fodbaldstreamsteamstitleplugin'
        ],
        'fodbaldstreamsteamslistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Teams/fodbaldstreamsteamslistplugin'
        ],

        //MATCH
        'fodbaldstreamsmatchheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Match/fodbaldstreamsmatchheadplugin'
        ],
        'fodbaldstreamsmatchcontentplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Match/fodbaldstreamsmatchcontentplugin'
        ],

        //LEAGUE
        'fodbaldstreamsleagueheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'League/fodbaldstreamsleagueheadplugin'
        ],
        'fodbaldstreamsleaguetitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'League/fodbaldstreamsleaguetitleplugin'
        ],
        'fodbaldstreamsleaguecontentplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'teams' => [],
                'schedule' => [],
                'colors' => []
            ],
            'template' => 'League/fodbaldstreamsleaguecontentplugin'
        ],

        //TEAM
        'fodbaldstreamsteamheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Team/fodbaldstreamsteamheadplugin'
        ],
        'fodbaldstreamsteamcontentplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'events' => [],
                'colors' => []
            ],
            'template' => 'Team/fodbaldstreamsteamcontentplugin'
        ],
    ];
}

function rp_cms_steve_integration_live_fodbald_streams_page_attachments(array &$page)
{	
	$page['#attached']['library'][] = 'rp_cms_steve_integration_live_fodbald_streams/LiveFodbaldStreamsAdmin';
	
	if(!\Drupal::service('router.admin_context')->isAdminRoute() && \Drupal::service('theme.manager')->getActiveTheme()->getName() == 'live_fodbald_streams'){
    	$page['#attached']['library'][] = 'rp_cms_steve_integration_live_fodbald_streams/LiveFodbaldStreamsGeneral';
    }
}

function rp_cms_steve_integration_live_fodbald_streams_preprocess_block(&$vars){
	
    $blocks = [];

    foreach ($blocks as $block) {
        if($vars['elements']['#plugin_id'] == $block){
            $vars['#cache']['max-age'] = 0;
        }
    }
    $vars['#cache']['max-age'] = 0;
}