<?php

/**
 * @file
 * Contains rp_client_base.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_client_base_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_client_base module.
    case 'help.page.rp_client_base':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Steve import base module ') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rp_client_base_theme() {
  return [
    'rp_client_base' => [
      'render element' => 'children',
    ],
  ];
}
