name: 'RP CMS - Sesport Block/Templete Configuration'
type: module
core: 8.x
description: Test Site configuration (using a Sesport Templete).Just for Test new code.
dependencies:
  - block
  - ctools
  - help
  - search
  - sesport_blocks
  - shortcut
  - system
package: 'Rebel Penguins CMS - Frontend'
