<?php

/**
 * @file
 * Contains rebelpenguin_endponts_client.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rebelpenguin_endponts_client_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rebelpenguin_endponts_client module.
    case 'help.page.rebelpenguin_endponts_client':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function rebelpenguin_endponts_client_theme() {
  return [
    'rebelpenguin_endponts_client' => [
      'template' => 'rebelpenguin_endponts_client',
      'render element' => 'children',
    ],
  ];
}
