<?php

/**
 * @file
 * Contains rp_cms_steve_integration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_cms_steve_integration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_cms_steve_integration module.
    case 'help.page.rp_cms_steve_integration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provide integration between Backend and Frontend on Steve CMS project') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rp_cms_steve_integration_theme() {
  return [
    'siteflagmenuplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/GeneralSite/siteflagmenuplugin',
      ],
    'sitefooterplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/GeneralSite/sitefooterplugin',
      ],
    'homebodyplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/HomePage/homebodyplugin',
      ],
    'homefooterplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/HomePage/homefooterplugin',
      ],
    'homeheadplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/HomePage/homeheadplugin',
      ],
    'homepartnerplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/HomePage/homepartnerplugin',
      ],
    'sporthomeheadplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/SportPage/sporthomeheadplugin',
      ],
    'sporthomepopularmatchplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/SportPage/sporthomepopularmatchplugin',
      ],
    'sporthomescheduleplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/SportPage/sporthomescheduleplugin',
      ],
    'sporthomestreamlistplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/SportPage/sporthomestreamlistplugin',
      ],
    'sporthomefooterplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/SportPage/sporthomefooterplugin',
      ],
    'sportblogheadplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/Blog/sportbloghead',
      ],
    'sportblogbodyplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/Blog/sportblogbody',
      ],
    'sportblogfooterplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/Blog/sportblogfooter',
      ],
    'eventpagecontentplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/Events/eventpagecontentplugin',
      ],
    'eventpagefooterplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/Events/eventpagefooterplugin',
      ],
    'eventpageheadplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/Events/eventpageheadplugin',
      ],
    'eventpagestreamlistplugin' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => [],
        ],
        'template' => 'SteveBaseFrontend/Events/eventpagestreamlistplugin',
      ],

  ];
}

