<?php

/**
 * @file
 * Contains rp_sport_info.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_sport_info_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_sport_info module.
    case 'help.page.rp_sport_info':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RP Sport Info Content') . '</p>';
      return $output;

    default:
  }
}
