<?php

/**
 * @file
 * Provides a site entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function rp_sites_theme() {
  return [
    'rp_site' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for site templates.
 *
 * Default template: rp-site.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the site information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_rp_site(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
