<?php

/**
 * @file
 * Contains rp_stream_provider_info.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_stream_provider_info_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_stream_provider_info module.
    case 'help.page.rp_stream_provider_info':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RP Stream Provider Info') . '</p>';
      return $output;

    default:
  }
}
