<?php
	
use Drupal\block\Entity\Block;

function rp_cms_steve_integration_se_fodbald_install() {
	$blocks = [];
	$blocks = \Drupal::entityTypeManager()
		->getStorage('block')
		->loadByProperties(['theme' => 'se_fodbald', 'region' => 'content']);
	
	if($blocks){
		foreach(array_keys($blocks) as $block){
			$block = Block::load($block);
			if($block->getPluginId() != 'system_main_block'){
				$block->setRegion('none');
				$block->save();
			}
		}
	}
}

