<?php

/**
 * @file
 * Contains rp_ad_block.module.
 */

/**
 * Implements hook_theme().
 */
function rp_ad_block_theme()
{
    return [
        'adblockplugin' => [
            'variables' => [
                'data' => []
            ],
            'template' => 'AdBlock/adblockplugin'
        ],
    ];
}

/**
 * Implements hook_page_attachments().
 */
function rp_ad_block_page_attachments(array &$page)
{	
	$page['#attached']['library'][] = 'rp_ad_block/AdBlockGeneral';
}

/**
 * Implements hook_preprocess_block().
 */
function rp_ad_block_preprocess_block(&$vars){
    $blocks = ['adblockplugin'];

    foreach ($blocks as $block) {
        if($vars['elements']['#plugin_id'] == $block){
            $vars['#cache']['max-age'] = 0;
        }
    }
}

/**
 * Implements hook_page_bottom().
 */
function rp_ad_block_page_bottom(&$variables){
	if(!\Drupal::service('router.admin_context')->isAdminRoute()){
		$block = \Drupal\block\Entity\Block::load('adblockplugin');
		$variables['adblockplugin'] = \Drupal::entityTypeManager()
		  ->getViewBuilder('block')
		  ->view($block);
	}
}