bundle: rp_cms
required:
  - language.mappings
  - language.negotiation
  - language.types
  - locale.settings
  - pathauto.settings
  - stevethemebase.settings
  - block.block.colormainmenublock
  - block.block.custombreadcrumbsblock
  - block.block.eventpagecontent
  - block.block.eventpagefooter
  - block.block.eventpagehead
  - block.block.eventpagestreamlist
  - block.block.homepagebody
  - block.block.homepagefooter
  - block.block.homepagepartners
  - block.block.homepagetophead
  - block.block.languageswitcher
  - block.block.livestreamreviewsblock
  - block.block.sitepagefooter
  - block.block.sitepagetop
  - block.block.sitepagetop_2
  - block.block.sitesportsubmenu
  - block.block.sportblogbody
  - block.block.sportblogfooter
  - block.block.sportbloghead
  - block.block.sportlivestreampagefooter
  - block.block.sportlivestreampagestreamlist
  - block.block.sportlivestreampagetop
  - block.block.sportpagefooter
  - block.block.sportpagepopularmatch
  - block.block.sportpageschedule
  - block.block.sportpagestreamlist
  - block.block.sportpagetop
  - block.block.stevethemebase_account_menu
  - block.block.stevethemebase_branding
  - block.block.stevethemebase_breadcrumbs
  - block.block.stevethemebase_content
  - block.block.stevethemebase_footer
  - block.block.stevethemebase_help
  - block.block.stevethemebase_local_actions
  - block.block.stevethemebase_local_tasks
  - block.block.stevethemebase_main_menu
  - block.block.stevethemebase_messages
  - block.block.stevethemebase_page_title
  - block.block.stevethemebase_powered
  - block.block.stevethemebase_search
  - block.block.stevethemebase_tools
  - language.entity.en
