<?php

/**
 * @file
 * Contains rp_site_info.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Field\FieldDefinitionInterface;

/**
 * Implements hook_help().
 */
function rp_site_info_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_site_info module.
    case 'help.page.rp_site_info':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RP Site Info extend site entity') . '</p>';
      return $output;

    default:
  }
}

function rp_site_info_get_config_name(EntityInterface $entity) {

	$config_name = '';

	$site_id = $entity->get('field_site_info_site')->target_id;
	$region_id = $entity->get('field_site_info_region')->target_id;
	$language_content_id = $entity->get('field_site_info_language')->target_id;

	if(!is_null($site_id) && !is_null($region_id) && !is_null($language_content_id)) {
		$site = \Drupal::entityTypeManager()->getStorage('site')->load($site_id);
		$region = \Drupal::entityTypeManager()->getStorage('region')->load($region_id);
		$language_content = \Drupal::entityTypeManager()->getStorage('language_content')->load($language_content_id);
		$site_code = $site->get('field_site_api_id')->value;
		//$site_code = strtolower(preg_replace('@[^a-z0-9_]+@','_',$site->getName()));
		$region_code = $region->get('field_region_code')->value;
		$language_content_code = $language_content->get('field_language_content_code')->value;

		$config_name = $site_code.'.'.$region_code.'.'.$language_content_code; 
	}

	return $config_name;

}

function rp_site_info_config_resource_fields(EntityInterface $entity) {

  $field_names = array_map(function (FieldDefinitionInterface $field_definition) {
    return $field_definition->getName();
  }, \Drupal::entityManager()->getFieldDefinitions('site_info', 'site_info') );

  $resourceFields = [];
  foreach($field_names as $field_name) {
  	if(substr($field_name,0,6) == 'field_' ) {
  		if(!in_array($field_name,['field_site_info_site','field_site_info_region','field_site_info_language'])) {
	  		$resourceFields[$field_name] = [
		      'fieldName' => $field_name,
		      'fieldValue' => $entity->get($field_name)->value,
	  		];
  		}
  		else {
  			$resourceFields[$field_name] = [
		      'fieldName' => $field_name,
		      'fieldValue' => $entity->get($field_name)->entity->getName(),
	  		];
  		}

  	}
  }

  return $resourceFields;
}

function rp_site_info_site_info_insert(EntityInterface $entity) {

	$config_name = rp_site_info_get_config_name($entity);

	if(!empty($config_name)) {
		$site_info_config = \Drupal::entityTypeManager()->getStorage('site_info_config')->load($config_name);
		if(is_null($site_info_config)) {
			$site_info_config = \Drupal::entityTypeManager()->getStorage('site_info_config')->create();
			$resourceFields = rp_site_info_config_resource_fields($entity);
			$site_info_config->set('id',$config_name);
			$site_info_config->set('label',$config_name);
			$site_info_config->set('site_info',$entity->id());
			$site_info_config->set('site_info_uuid',$entity->uuid());
			$site_info_config->set('site',$entity->get('field_site_info_site')->entity->get('field_site_api_id')->value);
			$site_info_config->set('region',$entity->get('field_site_info_region')->entity->get('field_region_code')->value);
			$site_info_config->set('language_content',$entity->get('field_site_info_language')->entity->get('field_language_content_code')->value);
			$site_info_config->set('resourceFields',$resourceFields);
			$site_info_config->save();
		}
	}

}

function rp_site_info_site_info_update(EntityInterface $entity) {

	$config_name = rp_site_info_get_config_name($entity);

	if(!empty($config_name)) {
		$site_info_config = \Drupal::entityTypeManager()->getStorage('site_info_config')->load($config_name);
		if(!is_null($site_info_config)) {
			$resourceFields = rp_site_info_config_resource_fields($entity);
			// $site_info_config->set('id',$config_name);
			// $site_info_config->set('label',$config_name);
			$site_info_config->set('site_info',$entity->id());
			$site_info_config->set('site_info_uuid',$entity->uuid());
			$site_info_config->set('resourceFields',$resourceFields);
			$site_info_config->save(); 
		}
	}

}