<?php

/**
 * @file
 * Contains rp_repo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_repo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_repo module.
    case 'help.page.rp_repo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rp_repo_theme() {
  return [
    'rp_repo' => [
      'render element' => 'children',
    ],
  ];
}
