rp_site_info.site_info_config.*:
  type: config_entity
  label: 'Site info config config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    # site:
    #   type: sequence
    #   label: "Site"
    #   sequence:
    #     type: mapping
    #     mapping:
    #       target_id:
    #         type: string
    # region:
    #   type: sequence
    #   label: "Region"
    #   sequence:
    #     type: mapping
    #     mapping:
    #       target_id:
    #         type: string
    # language_content:
    #   type: sequence
    #   label: "Language content"
    #   sequence:
    #     type: mapping
    #     mapping:
    #       target_id:
    #         type: string
    # site_info:
    #   type: sequence
    #   label: "Site info"
    #   sequence:
    #     type: mapping
    #     mapping:
    #       target_id:
    #         type: string
    site_info:
      type: string
      label: "Site info"
    site_info_uuid:
      type: string
      label: "Site info UUID"
    site:
      type: string
      label: "Site"
    region:
      type: string
      label: "Region"
    language_content:
      type: string
      label: "Language content"
    resourceFields:
      type: sequence
      label: 'Fields'
      sequence:
        type: rp_site_info.resource_field

rp_site_info.resource_field:
  type: mapping
  mapping:
    fieldName:
      type: string
      label: 'Entity field name'
    fieldValue:
      type: string
      label: 'Entity field value'