<?php

/**
 * @file
 * Contains rp_cms_steve_integration.module.
 */
 
use Drupal\rp_cms_steve_integration_live_fodbald\Controller\LiveFodbaldController;
use Drupal\Core\Language\LanguageInterface;

/**
 * Implements hook_theme().
 */

function rp_cms_steve_integration_live_fodbald_theme()
{
    return [
        //PAGES
        'fodbaldhomepage' => [
            'template' => 'Pages/fodbaldhomepage'
        ],
        'fodbaldprogrampage' => [
            'template' => 'Pages/fodbaldprogrampage'
        ],
        'fodbaldproviderspage' => [
            'template' => 'Pages/fodbaldproviderspage'
        ],
        'fodbaldleaguespage' => [
            'template' => 'Pages/fodbaldleaguespage'
        ],
        'fodbaldteamspage' => [
            'template' => 'Pages/fodbaldteamspage'
        ],
        'fodbaldpreviewspage' => [
            'template' => 'Pages/fodbaldpreviewspage'
        ],
        'fodbaldmatchpage' => [
            'template' => 'Pages/fodbaldmatchpage'
        ],
        'fodbaldpreviewpage' => [
            'template' => 'Pages/fodbaldpreviewpage'
        ],
        'fodbaldleaguepage' => [
            'template' => 'Pages/fodbaldleaguepage'
        ],
        'fodbaldteampage' => [
            'template' => 'Pages/fodbaldteampage'
        ],
        //GENERAL
        'fodbaldheaderplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Site/fodbaldheaderplugin'
        ],
        'fodbaldfooterplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Site/fodbaldfooterplugin'
        ],
        'fodbaldfootersecondaryplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => [],
                'front' => FALSE,
            ],
            'template' => 'Site/fodbaldfootersecondaryplugin'
        ],

        //HOME PAGE
        'fodbaldhomeheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldhomeheadplugin'
        ],
        'fodbaldhometitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldhometitleplugin'
        ],
        'fodbaldhomematchesplugin' => [
            'variables' => [
                'tags' => [],
                'article' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldhomematchesplugin'
        ],
        'fodbaldhomefeaturesplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldhomefeaturesplugin'
        ],
        'fodbaldhometabsplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Home/fodbaldhometabsplugin'
        ],
        //PROGRAM
        'fodbaldprogramheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Program/fodbaldprogramheadplugin'
        ],
        'fodbaldprogramtitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Program/fodbaldprogramtitleplugin'
        ],
        'fodbaldprogrammatchlistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Program/fodbaldprogrammatchlistplugin'
        ],
        //PROVIDERS
        'fodbaldprovidersheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Providers/fodbaldprovidersheadplugin' 
        ],
        'fodbaldproviderslistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Providers/fodbaldproviderslistplugin' 
        ],
        //LEAGUES
        'fodbaldleaguesheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Leagues/fodbaldleaguesheadplugin'
        ],
        'fodbaldleaguestitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Leagues/fodbaldleaguestitleplugin'
        ],
        'fodbaldleagueslistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Leagues/fodbaldleagueslistplugin'
        ],
        //TEAMS
        'fodbaldteamsheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Teams/fodbaldteamsheadplugin'
        ],
        'fodbaldteamstitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Teams/fodbaldteamstitleplugin'
        ],
        'fodbaldteamslistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Teams/fodbaldteamslistplugin'
        ],
        //PREVIEWS
        'fodbaldpreviewslistplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Previews/fodbaldpreviewslistplugin'
        ],
        //MATCH
        'fodbaldmatchheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Match/fodbaldmatchheadplugin'
        ],
        'fodbaldmatchtitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Match/fodbaldmatchtitleplugin'
        ],
        'fodbaldmatchprovidersplugin' => [
            'variables' => [
                'tags' => [],
                'article' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Match/fodbaldmatchprovidersplugin'
        ],
        'fodbaldmatchfeaturesplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Match/fodbaldmatchfeaturesplugin'
        ],
        //PREVIEW
        'fodbaldpreviewheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Preview/fodbaldpreviewheadplugin'
        ],
        'fodbaldpreviewtitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Preview/fodbaldpreviewtitleplugin'
        ],
        'fodbaldpreviewprovidersplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Preview/fodbaldpreviewprovidersplugin'
        ],
        'fodbaldpreviewarticleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Preview/fodbaldpreviewarticleplugin'
        ],
        'fodbaldpreviewfeaturesplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Preview/fodbaldpreviewfeaturesplugin'
        ],
        //LEAGUE
        'fodbaldleagueheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'League/fodbaldleagueheadplugin'
        ],
        'fodbaldleaguetitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'League/fodbaldleaguetitleplugin'
        ],
        'fodbaldleagueprovidersplugin' => [
            'variables' => [
                'tags' => [],
                'schedule' => [],
                'info' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'League/fodbaldleagueprovidersplugin'
        ],
        'fodbaldleaguefeaturesplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'League/fodbaldleaguefeaturesplugin'
        ],
        //TEAM
        'fodbaldteamheadplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Team/fodbaldteamheadplugin'
        ],
        'fodbaldteamtitleplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Team/fodbaldteamtitleplugin'
        ],
        'fodbaldteamprovidersplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Team/fodbaldteamprovidersplugin'
        ],
        'fodbaldteamfeaturesplugin' => [
            'variables' => [
                'tags' => [],
                'background' => [],
                'colors' => []
            ],
            'template' => 'Team/fodbaldteamfeaturesplugin'
        ],
        'fodbaldpopupplugin' => [
	      'variables' => [
		        'tags' => [],
                'background' => [],
                'colors' => []
	      ],
	      'template' => 'PopUp/fodbaldpopupplugin'
        ],
    ];
}

function getFodbaldClass(){
	static $class = NULL;
	
	if(!$class){
		$class = new LiveFodbaldController();
	}
	
	return $class;
}

function rp_cms_steve_integration_live_fodbald_entity_insert(Drupal\Core\Entity\EntityInterface $entity){
	if($entity->bundle() == 'events' && $entity->field_event_article->value){

		$alias = getFodbaldClass()->generateEventArticleAlias($entity);
		
		if($alias){			
			\Drupal::service('path.alias_storage')->save($alias['source'], $alias['alias'], $alias['langcode']);
		}
	}
}

function rp_cms_steve_integration_live_fodbald_entity_update(Drupal\Core\Entity\EntityInterface $entity){
	if($entity->bundle() == 'events' && $entity->field_event_article->value && $entity->field_event_article->value !== $entity->original->field_event_article->value){

		$alias = getFodbaldClass()->generateEventArticleAlias($entity);
		
		if($alias){
			\Drupal::service('path.alias_storage')->save($alias['source'], $alias['alias'], $alias['langcode']);
		}
	}
}

function rp_cms_steve_integration_live_fodbald_page_attachments(array &$page)
{	
	$page['#attached']['library'][] = 'rp_cms_steve_integration_live_fodbald/LiveFodbaldAdmin';

	if(!\Drupal::service('router.admin_context')->isAdminRoute() && \Drupal::service('theme.manager')->getActiveTheme()->getName() == 'live_fodbald'){
    	$page['#attached']['library'][] = 'rp_cms_steve_integration_live_fodbald/LiveFodbaldGeneral';
    }
}

function rp_cms_steve_integration_live_fodbald_preprocess_block(&$vars){
	
    $blocks = ['fodbaldprogrammatchlistplugin', 'fodbaldteamslistplugin', 'fodbaldhometabsplugin', 'fodbaldhomematchesplugin', 'fodbaldpreviewslistplugin'];

    foreach ($blocks as $block) {
        if($vars['elements']['#plugin_id'] == $block){
            $vars['#cache']['max-age'] = 0;
        }
    }
}