<?php

/**
 * @file
 * Contains rp_repoapi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_repoapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_repoapi module.
    case 'help.page.rp_repoapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RP Repo API Connexions to RP Repo API') . '</p>';
      return $output;

    default:
  }
}
