<?php

/**
 * @file
 * Contains rp_admin_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_admin_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_admin_events module.
    case 'help.page.rp_admin_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Events Administration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rp_admin_events_theme() {
  return [
    'rp_admin_events' => [
      'render element' => 'children',
    ],
  ];
}
