<?php
/**
 * @file
 * Contains sesport_blocks.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sesport_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sesport_blocks module.
    case 'help.page.sesport_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sesport_blocks_theme($existing, $type, $theme, $path) {
  return [

    //General

    'sesport_blocks' =>
      [
        'variables' => [
          'titulo' => 'Udbydere af Live Stream',
          'descripcion' => 'Læs om de forskellige udbydere af live stream på det danske marked.',
          'tags' => array()
        ],
        'template' => 'GeneralPages/sesport-blocks'
      ],
    'sesport_review' =>
      [
        'variables' => [
          'titulo' => 'Find de bedste provider Reviews',
          'descripcion' => 'Vi har på SeSport samlet, beskrevet og vurderet de forskellige sportsbookmakere på det danske marked. Læs anmeldelserne og find din favorit!',
          'tags' => array()
        ],
        'template' => 'GeneralPages/sesport-review'
      ],
    'sesport_topMenu' =>
      [
        'variables' => [
          'titulo' => 'sesport top Menu',
          'descripcion' => 'sesport_topMenu',
          'tags' => array()
        ],
        'template' => 'GeneralPages/sesport-topMenu'
      ],

    //Front Page

    'sesport_front_stream' =>
      [
        'variables' => [
          'titulo' => 'Find din live stream udbyder',
          'descripcion' => 'Find din live stream udbyder',
          'tags' => array()
        ],
        'template' => 'SportFrontPage/sesport-front-stream'
      ],
    'sesport_front_kampprogram' =>
      [
        'variables' => [
          'titulo' => 'Find din live stream udbyder',
          'descripcion' => 'Find din live stream udbyder',
          'tags' => array()
        ],
        'template' => 'SportFrontPage/sesport-front-kampprogram'
      ],
    'sesport_frontpage_head' =>
      [
        'variables' => [
          'titulo' => 'Find din live stream udbyder',
          'descripcion' => 'Find din live stream udbyder',
          'tags' => array()
        ],
        'template' => 'SportFrontPage/sesport-frontpage-head'
      ],
      'sesport_frontpage_topevents' =>
      [
        'variables' => [
          'titulo' => 'Find din live stream udbyder',
          'descripcion' => 'Find din live stream udbyder',
          'tags' => array()
        ],
        'template' => 'SportFrontPage/sesport-frontpage-topevents'
      ],

    //Live Stream

    'sesport_livestream_carrousel' =>
      [
        'variables' => [
          'titulo' => 'sesport top Menu',
          'descripcion' => 'sesport_livestream_carrousel',
          'tags' => array()
        ],
        'template' => 'LiveStreamPages/sesport-livestream-carrousel'
      ],
    'sesport_livestream_schedule' =>
      [
        'variables' => [
          'titulo' => 'sesport top Menu',
          'descripcion' => 'sesport_livestream_schedule',
          'tags' => array()
        ],
        'template' => 'LiveStreamPages/sesport-livestream-schedule'
      ],
    'sesport_livestream_streamlist' =>
      [
        'variables' => [
          'titulo' => 'sesport top Menu',
          'descripcion' => 'sesport_livestream_streamlist',
          'tags' => array()
        ],
        'template' => 'LiveStreamPages/sesport-livestream-streamlist'
      ],

    //Game Pages

    'sesport_head_gamepage' =>
      [
        'variables' => [
          'titulo' => 'sesport top Menu',
          'descripcion' => 'sesport_livestream_streamlist',
          'tags' => array()
        ],
        'template' => 'GamePages/sesport-head-gamepages'
      ]
  ];
}
