<?php

/**
 * @file
 * Contains rp_cms_site_info.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_cms_site_info_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_cms_site_info module.
    case 'help.page.rp_cms_site_info':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RP CMS Site Info sync with api') . '</p>';
      return $output;

    default:
  }
}
