<?php

/**
 * @file
 * Contains rp_cms_theme_interaction.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_cms_theme_interaction_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_cms_theme_interaction module.
    case 'help.page.rp_cms_theme_interaction':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Interaction whit Themplate RP Base - Supply all data.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rp_cms_theme_interaction_theme() {
  return [
    'rp_cms_theme_interaction' => [
      'render element' => 'children',
    ],
  ];
}
