<?php

/**
 * @file
 * Contains rp_participant.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_participant_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_participant module.
    case 'help.page.rp_participant':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('RP Participant') . '</p>';
      return $output;

    default:
  }
}
