rp_cms_site_info.cms_site_info.*:
  type: config_entity
  label: 'CMS Site Info config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    site:
      type: sequence
      label: "Site"
      sequence:
        type: mapping
        mapping:
          target_id:
            type: string
    region:
      type: sequence
      label: "Region"
      sequence:
        type: mapping
        mapping:
          target_id:
            type: string
    language_content:
      type: sequence
      label: "Language content"
      sequence:
        type: mapping
        mapping:
          target_id:
            type: string
    site_info:
      type: sequence
      label: "Site info"
      sequence:
        type: mapping
        mapping:
          target_id:
            type: string
    resourceFields:
      type: sequence
      label: 'Fields'
      sequence:
        type: rp_site_info.resource_field

rp_site_info.resource_field:
  type: mapping
  mapping:
    fieldName:
      type: string
      label: 'Entity field name'
    fieldValue:
      type: string
      label: 'Entity field value'