<?php

/**
 * @file
 * Contains rp_block_data_configuration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rp_block_data_configuration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rp_block_data_configuration module.
    case 'help.page.rp_block_data_configuration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configuration of our modules') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rp_block_data_configuration_theme() {
  return [
    'rp_block_data_configuration' => [
      'render element' => 'children',
    ],
  ];
}
